### ISSUE TITLE
device is correct?

### ISSUE THREAD

**Issue by rsc9421** [Palmitoxico/STM32F103_Template#1]
Hi, in makefile it say "DEVICE     = STM32F103xB" it's correct for stm32f103c8t6?

**Comment by augustofg** [comment]
This is used to define the STM32F103xB macro required by the stm32f1xx.h header. I think the correct device macro name should be STM32F103x6. I'll take a look on this.

Seems that these microcontrollers are very similar so I've never noticed this.

**Comment by augustofg** [comment]
I've checked the STMCubeMX generated headers for the STM32F103C8Tx microcontroller and the STM32F103xB macro is defined, so it is correct.
